// <auto-generated />
namespace WebShop_NhomHardTech.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddtableProducttoDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtableProducttoDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202203290736009_Add table Product to Db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
